### PR TITLE
Verifybamid_v2.1.0 App directory updated

### PR DESCRIPTION
**Pull request by carmelinacharalambous**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3)* status: all files reviewed, 6 unresolved discussions (waiting on @carmelinacharalambous)

___
*[dxapp.json, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXI-QkCv_-7vGKLDMj:-MSXI-QkCv_-7vGKLDMk:bky9yb6) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/dxapp.json#L2)):*
> ```JSON
> {
>   "name": "verifybamid_v2.0.1",
> ```

This change is adding functionality, so would increment the middle number in the version, rather than the last number  (which is for bug fix updates)
So new version should be 2.1.0
___
*[dxapp.json, line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXIJmT0YspJKIvkmrd:-MSXIJmT0YspJKIvkmre:b-w0gfr) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/dxapp.json#L4)):*
> ```
> 2.0.0
> ```
Doesn't match version above
___
*[dxapp.json, line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXIP6n7ikhg0ISIQSt:-MSXIP6n7ikhg0ISIQSu:bb3cg0l) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/dxapp.json#L11)):*
> ```
> v2.0.1
> ```
2.1.0
___
*[dxapp.json, line 33 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXJ0wG2iwo2Fngj10E:-MSXJ0wG2iwo2Fngj10F:b9fie0n) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/dxapp.json#L33)):*
> ```
> SNPs to
> ```
the SNPs used to
___
*[resources/home/dnanexus/Omni25_genotypes_1525_samples_v2.b38.PASS.ALL.sites.vcf.gz, line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXLBggAQ6VPohSChAQ:-MSXLBggAQ6VPohSChAR:b-u8k5km) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/resources/home/dnanexus/Omni25_genotypes_1525_samples_v2.b38.PASS.ALL.sites.vcf.gz#L0)):*
Does this vcf (and the 37 vcf) need to be part of the app? It seems to be no longer used.

The app was modified to take vcf as input. I assume this means the vcf is to be stored in 001, so it's no longer beneficial to include it in the app
___
*[src/code.sh, line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXKoIs4OkQ1ANshBEh:-MSXKoIs4OkQ1ANshBEi:b-scngb9) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/src/code.sh#L46)):*
> ```
> dx-upload-all-outputs
> ```
Missing newline at eof

**Comment by carmelinacharalambous** [comment]
Pull request information:

verifybamid_v.2.1.0 a new app input created for SNPs vcf (verifybamid_v2.0.0 had GRCh37 vcf as a static file). This allows users to select which version of the snps vcf is required (GRCh37/ GRCh38) prior to running the app.

- new app input in json file
- new app version verifybamid_v2.1.0
- change code.sh line 31 added: dx download "$vcf_file" -o vcf_file
- change code.sh line 40 --vcf vcf_file

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3)* status: all files reviewed, 1 unresolved discussion (waiting on @carmelinacharalambous)

___
*[dxapp.json, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXI-QkCv_-7vGKLDMj:-MSc4GVG9cByMwBAzvj2:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/dxapp.json#L2)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

This change is adding functionality, so would increment the middle number in the version, rather than the last number  (which is for bug fix updates)
So new version should be 2.1.0
</blockquote></details>

Done
___
*[dxapp.json, line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXIJmT0YspJKIvkmrd:-MSc4MzkA-UiLcutHUKx:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/dxapp.json#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 2.0.0
> ```
Doesn't match version above
</blockquote></details>

Done
___
*[dxapp.json, line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXIP6n7ikhg0ISIQSt:-MSc4PHm8fklDmh3Lnfg:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/dxapp.json#L11)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> v2.0.1
> ```
2.1.0
</blockquote></details>

Done
___
*[dxapp.json, line 33 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXJ0wG2iwo2Fngj10E:-MSc4STpEOUV5s-fqAHj:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/dxapp.json#L33)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> SNPs to
> ```
the SNPs used to
</blockquote></details>

Done
___
*[resources/home/dnanexus/Omni25_genotypes_1525_samples_v2.b38.PASS.ALL.sites.vcf.gz, line  at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXLBggAQ6VPohSChAQ:-MSc4feU0DjWpeNeLnA5:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/resources/home/dnanexus/Omni25_genotypes_1525_samples_v2.b38.PASS.ALL.sites.vcf.gz#L)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does this vcf (and the 37 vcf) need to be part of the app? It seems to be no longer used.

The app was modified to take vcf as input. I assume this means the vcf is to be stored in 001, so it's no longer beneficial to include it in the app
</blockquote></details>

Done
___
*[src/code.sh, line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSXKoIs4OkQ1ANshBEh:-MSc4kW4C0XbwLAyK48Q:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c8f964cf94da57fe9c438a812efb39219812a86d/src/code.sh#L46)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> dx-upload-all-outputs
> ```
Missing newline at eof
</blockquote></details>

Done
___
*[src/code.sh, line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSc5XRF87L9D8bUEUSm:-MSc5XRF87L9D8bUEUSn:bskls6k) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/01692917a331ec0448d698e0f1698aa3d238f0ee/src/code.sh#L2)):*
> ```
> v2.1.0 2.1.0
> ```
version duplicated

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/code.sh, line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/3#-MSc5XRF87L9D8bUEUSm:-MSc6kYH4KyqQ0YZHw76:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/01692917a331ec0448d698e0f1698aa3d238f0ee/src/code.sh#L2)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> v2.1.0 2.1.0
> ```
version duplicated
</blockquote></details>

Done

**Pull request merged**
