### PR TITLE
Di 164 into master 

### PR DESCRIPTION
**Pull request by Emma-MacK**
Changes made to produce eggd_VerifyBamID_v2.2.1:

- Update instance type
- Add licence file 
- Update version
- Update what's new section

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/7)

### CODE REVIEW

**Review by sophie22 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by sophie22 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/7)* status: all files reviewed, 1 unresolved discussion (waiting on @Emma-MacK and @mattgarner)

___
*[`dxapp.json` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/7#-NQ_E0l8-WhLMx8-4r1s:-NQ_E0l8-WhLMx8-4r1t:b-x37uiv) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/a9245eb2aa76ebce5500443885553481d8fd8c78/dxapp.json#L4)):*
> ```JSON
>   "name": "eggd_verifybamid", 
>   "title": "verifyBamID",
>   "summary": "v2.2.1 - Detects sample contamination from genotypic profiles; forked from moka-guys v1.1.1",
> ```

in the READme it says that current app is based on moka-guys version v1.2.0



_Code quote:_
```JSON
v1.1.1
```

**Review by Emma-MacK — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/7)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @sophie22)

___
*[`dxapp.json` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/7#-NQ_E0l8-WhLMx8-4r1s:-NR2VxLdCZFADtSUTPWu:b-770z2x) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/a9245eb2aa76ebce5500443885553481d8fd8c78/dxapp.json#L4)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

in the READme it says that current app is based on moka-guys version v1.2.0
</blockquote></details>

Good catch, I'll fix that now

**Review by sophie22 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Pull request merged**
